name: EditorConfig Checker

on:
  pull_request:
    branches:
      - master

jobs:
  editorconfig:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@main
      - uses: editorconfig-checker/action-editorconfig-checker@v2
      - run: editorconfig-checker
